CREATE TABLE [dbo].[CPClientCustomAttributeAudit] (
    [pk]                        DECIMAL (18)  IDENTITY (1, 1) NOT NULL,
    [AuditStartDate]            DATETIME      NULL,
    [AuditEndDate]              DATETIME      NULL,
    [AuditUser]                 VARCHAR (50)  NULL,
    [AuditMachine]              VARCHAR (15)  NULL,
    [AuditDeleted]              TINYINT       NULL,
    [pkCPClientCustomAttribute] DECIMAL (18)  NOT NULL,
    [fkCPClient]                DECIMAL (18)  NOT NULL,
    [DATA1]                     VARCHAR (250) NULL,
    [DATA2]                     VARCHAR (250) NULL,
    [DATA3]                     VARCHAR (250) NULL,
    [DATA4]                     VARCHAR (250) NULL,
    [DATA5]                     VARCHAR (250) NULL,
    [DATA6]                     VARCHAR (250) NULL,
    [DATA7]                     VARCHAR (250) NULL,
    [DATA8]                     VARCHAR (250) NULL,
    [DATA9]                     VARCHAR (250) NULL,
    [DATA10]                    VARCHAR (250) NULL,
    [DATA11]                    VARCHAR (250) NULL,
    [DATA12]                    VARCHAR (250) NULL,
    [DATA13]                    VARCHAR (250) NULL,
    [DATA14]                    VARCHAR (250) NULL,
    [DATA15]                    VARCHAR (250) NULL,
    [DATA16]                    VARCHAR (250) NULL,
    [DATA17]                    VARCHAR (250) NULL,
    [DATA18]                    VARCHAR (250) NULL,
    [DATA19]                    VARCHAR (250) NULL,
    [DATA20]                    VARCHAR (250) NULL,
    [DATA21]                    VARCHAR (250) NULL,
    [DATA22]                    VARCHAR (250) NULL,
    [DATA23]                    VARCHAR (250) NULL,
    [DATA24]                    VARCHAR (250) NULL,
    [DATA25]                    VARCHAR (250) NULL,
    [DATA26]                    VARCHAR (250) NULL,
    [DATA27]                    VARCHAR (250) NULL,
    [DATA28]                    VARCHAR (250) NULL,
    [DATA29]                    VARCHAR (250) NULL,
    [DATA30]                    VARCHAR (250) NULL,
    [DATA31]                    VARCHAR (250) NULL,
    [DATA32]                    VARCHAR (250) NULL,
    [DATA33]                    VARCHAR (250) NULL,
    [DATA34]                    VARCHAR (250) NULL,
    [DATA35]                    VARCHAR (250) NULL,
    [DATA36]                    VARCHAR (250) NULL,
    [DATA37]                    VARCHAR (250) NULL,
    [DATA38]                    VARCHAR (250) NULL,
    [DATA39]                    VARCHAR (250) NULL,
    [DATA40]                    VARCHAR (250) NULL,
    CONSTRAINT [PK_CPClientCustomAttributeAudit] PRIMARY KEY NONCLUSTERED ([pk] ASC)
);


GO
CREATE NONCLUSTERED INDEX [idxPkCPClientCustomAttributeAudit]
    ON [dbo].[CPClientCustomAttributeAudit]([pkCPClientCustomAttribute] ASC);

