CREATE TABLE [dbo].[OBUserSession] (
    [OBUserName]        VARCHAR (50)  NOT NULL,
    [SessionID]         VARCHAR (50)  NOT NULL,
    [ServiceURL]        VARCHAR (100) NOT NULL,
    [ServiceDataSource] VARCHAR (100) NOT NULL,
    [SessionOpenTime]   DATETIME      CONSTRAINT [DF_OBUserSession_SessionOpenTime] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_OBUserSession] PRIMARY KEY CLUSTERED ([OBUserName] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Holds currently active OnBase user sessions', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OBUserSession';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'OnBase user name', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OBUserSession', @level2type = N'COLUMN', @level2name = N'OBUserName';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'OnBase session ID generated by the OnBase application server', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OBUserSession', @level2type = N'COLUMN', @level2name = N'SessionID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'URL of the OnBase application server', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OBUserSession', @level2type = N'COLUMN', @level2name = N'ServiceURL';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'OnBase data source name', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OBUserSession', @level2type = N'COLUMN', @level2name = N'ServiceDataSource';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Time that the session was opened', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OBUserSession', @level2type = N'COLUMN', @level2name = N'SessionOpenTime';

